<h2>Analise da tabela do Campeonato Brasileiro de 2003 a 2022</h2>

Legenda:

Qual equipe venceu o campeonato mais vezes ao longo dos anos?

In [1]:
#Importando a biblioteca pandas 
import pandas as pd

In [2]:
# criando uma variável para receber o dataset em csv
brasileirao = pd.read_excel('brasileirao2.xlsx')

In [3]:
#Analisando o conjunto de dados
brasileirao.head()

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
0,2003,1,Cruzeiro,100,46,31,7,8,102,47,55,138,72.46
1,2003,2,Santos,87,46,25,12,9,93,60,33,138,63.04
2,2003,3,São Paulo,78,46,22,12,12,81,67,14,138,56.52
3,2003,4,São Caetano,74,46,19,14,13,53,37,16,138,53.62
4,2003,5,Coritiba,73,46,21,10,15,67,58,9,138,52.90

In [4]:
brasileirao.tail()

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
405,2022,16,Cuiabá,41,38,10,11,17,31,42,-11,114,35.96
406,2022,17,Ceará,37,38,7,16,15,34,41,-7,114,32.46
407,2022,18,Atlético Goianiense,36,38,8,12,18,39,57,-18,114,31.58
408,2022,19,Avaí,35,38,9,8,21,34,60,-26,114,30.70
409,2022,20,Juventude,22,38,3,13,22,29,69,-40,114,19.30

<h5>Verificar times duplicados ou com escrita incorreta</h5>

In [5]:
equipes_totais = brasileirao['equipe'].value_counts()

In [6]:
equipes_totais

São Paulo                 20
Santos                    20
Flamengo                  20
Fluminense                20
Corinthians               19
Internacional             19
Atlético Mineiro          19
Grêmio                    18
Cruzeiro                  17
Palmeiras                 17
Botafogo                  17
Atlético Paranaense       15
Vasco da Gama             15
Coritiba                  14
Goiás                     14
Figueirense               11
Bahia                     10
Vitória                   10
Ponte Preta                9
Sport                      9
Juventude                  7
Chapecoense                7
Avaí                       7
Atlético Goianiense        7
Ceará                      7
Fortaleza                  7
Paraná                     6
Náutico                    5
América Mineiro            5
Criciúma                   4
São Caetano                4
Guarani                    3
Portuguesa                 3
Paysandu                   3
Athletico Paranaense       3
RB Bragantino              2
Cuiabá                     2
Sport Recife               2
Santa Cruz                 2
Palmeirasa?                1
Athletico Paranaenseb?     1
CSA                        1
América de Natal           1
Joinville                  1
Grêmio Prudente            1
Santo André                1
Grêmio Barueri             1
Ipatinga                   1
Brasiliense                1
Red Bull Bragantino        1
Name: equipe, dtype: int64

In [7]:
equipes_totaisDF = pd.DataFrame(equipes_totais)
equipes_totaisDF

                        equipe
São Paulo                   20
Santos                      20
Flamengo                    20
Fluminense                  20
Corinthians                 19
Internacional               19
Atlético Mineiro            19
Grêmio                      18
Cruzeiro                    17
Palmeiras                   17
Botafogo                    17
Atlético Paranaense         15
Vasco da Gama               15
Coritiba                    14
Goiás                       14
Figueirense                 11
Bahia                       10
Vitória                     10
Ponte Preta                  9
Sport                        9
Juventude                    7
Chapecoense                  7
Avaí                         7
Atlético Goianiense          7
Ceará                        7
Fortaleza                    7
Paraná                       6
Náutico                      5
América Mineiro              5
Criciúma                     4
São Caetano                  4
Guarani                      3
Portuguesa                   3
Paysandu                     3
Athletico Paranaense         3
RB Bragantino                2
Cuiabá                       2
Sport Recife                 2
Santa Cruz                   2
Palmeirasa?                  1
Athletico Paranaenseb?       1
CSA                          1
América de Natal             1
Joinville                    1
Grêmio Prudente              1
Santo André                  1
Grêmio Barueri               1
Ipatinga                     1
Brasiliense                  1
Red Bull Bragantino          1

In [8]:
brasileirao.loc[brasileirao['equipe'] == 'Palmeirasa?']

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
372,2021,3,Palmeirasa?,66,38,20,6,12,58,43,15,114,57.89

In [9]:
brasileirao.loc[brasileirao['ano'] == 2021]

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
370,2021,1,Atlético Mineiro,84,38,26,6,6,67,34,33,114,73.68
371,2021,2,Flamengo,71,38,21,8,9,69,36,33,114,62.28
372,2021,3,Palmeirasa?,66,38,20,6,12,58,43,15,114,57.89
373,2021,4,Fortaleza,58,38,17,7,14,44,45,-1,114,50.88
374,2021,5,Corinthians,57,38,15,12,11,40,36,4,114,50.00
375,2021,6,RB Bragantino,56,38,14,14,10,55,46,9,114,49.12
376,2021,7,Fluminense,54,38,15,9,14,38,38,0,114,47.37
377,2021,8,América Mineiro,53,38,13,14,11,41,37,4,114,46.49
378,2021,9,Atlético Goianiense,53,38,13,14,11,33,36,-3,114,46.49
379,2021,10,Santos,50,38,12,14,12,35,40,-5,114,43.86
380,2021,11,Ceará,50,38,11,17,10,39,38,1,114,43.86
381,2021,12,Internacional,48,38,12,12,14,44,42,2,114,42.11
382,2021,13,São Paulo,48,38,11,15,12,31,39,-8,114,42.11
383,2021,14,Athletico Paranaenseb?,47,38,13,8,17,41,45,-4,114,41.23
384,2021,15,Cuiabá,47,38,10,17,11,34,37,-3,114,41.23
385,2021,16,Juventude,46,38,11,13,14,36,44,-8,114,40.35
386,2021,17,Grêmio,43,38,12,7,19,44,51,-7,114,37.72
387,2021,18,Bahia,43,38,11,10,17,42,51,-9,114,37.72
388,2021,19,Sport Recife,38,38,9,11,18,24,37,-13,114,33.33
389,2021,20,Chapecoense,15,38,1,12,25,27,67,-40,114,13.16

In [10]:
brasileirao.loc[brasileirao['equipe'] == 'Palmeirasa?', 'equipe'] = 'Palmeiras'

In [11]:
brasileirao.loc[brasileirao['ano'] == 2021]

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
370,2021,1,Atlético Mineiro,84,38,26,6,6,67,34,33,114,73.68
371,2021,2,Flamengo,71,38,21,8,9,69,36,33,114,62.28
372,2021,3,Palmeiras,66,38,20,6,12,58,43,15,114,57.89
373,2021,4,Fortaleza,58,38,17,7,14,44,45,-1,114,50.88
374,2021,5,Corinthians,57,38,15,12,11,40,36,4,114,50.00
375,2021,6,RB Bragantino,56,38,14,14,10,55,46,9,114,49.12
376,2021,7,Fluminense,54,38,15,9,14,38,38,0,114,47.37
377,2021,8,América Mineiro,53,38,13,14,11,41,37,4,114,46.49
378,2021,9,Atlético Goianiense,53,38,13,14,11,33,36,-3,114,46.49
379,2021,10,Santos,50,38,12,14,12,35,40,-5,114,43.86
380,2021,11,Ceará,50,38,11,17,10,39,38,1,114,43.86
381,2021,12,Internacional,48,38,12,12,14,44,42,2,114,42.11
382,2021,13,São Paulo,48,38,11,15,12,31,39,-8,114,42.11
383,2021,14,Athletico Paranaenseb?,47,38,13,8,17,41,45,-4,114,41.23
384,2021,15,Cuiabá,47,38,10,17,11,34,37,-3,114,41.23
385,2021,16,Juventude,46,38,11,13,14,36,44,-8,114,40.35
386,2021,17,Grêmio,43,38,12,7,19,44,51,-7,114,37.72
387,2021,18,Bahia,43,38,11,10,17,42,51,-9,114,37.72
388,2021,19,Sport Recife,38,38,9,11,18,24,37,-13,114,33.33
389,2021,20,Chapecoense,15,38,1,12,25,27,67,-40,114,13.16

In [12]:
brasileirao.loc[brasileirao['equipe'] == 'Athletico Paranaenseb?', 'equipe'] = 'Athletico Paranaense'

In [13]:
brasileirao.loc[brasileirao['ano'] == 2021]

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
370,2021,1,Atlético Mineiro,84,38,26,6,6,67,34,33,114,73.68
371,2021,2,Flamengo,71,38,21,8,9,69,36,33,114,62.28
372,2021,3,Palmeiras,66,38,20,6,12,58,43,15,114,57.89
373,2021,4,Fortaleza,58,38,17,7,14,44,45,-1,114,50.88
374,2021,5,Corinthians,57,38,15,12,11,40,36,4,114,50.00
375,2021,6,RB Bragantino,56,38,14,14,10,55,46,9,114,49.12
376,2021,7,Fluminense,54,38,15,9,14,38,38,0,114,47.37
377,2021,8,América Mineiro,53,38,13,14,11,41,37,4,114,46.49
378,2021,9,Atlético Goianiense,53,38,13,14,11,33,36,-3,114,46.49
379,2021,10,Santos,50,38,12,14,12,35,40,-5,114,43.86
380,2021,11,Ceará,50,38,11,17,10,39,38,1,114,43.86
381,2021,12,Internacional,48,38,12,12,14,44,42,2,114,42.11
382,2021,13,São Paulo,48,38,11,15,12,31,39,-8,114,42.11
383,2021,14,Athletico Paranaense,47,38,13,8,17,41,45,-4,114,41.23
384,2021,15,Cuiabá,47,38,10,17,11,34,37,-3,114,41.23
385,2021,16,Juventude,46,38,11,13,14,36,44,-8,114,40.35
386,2021,17,Grêmio,43,38,12,7,19,44,51,-7,114,37.72
387,2021,18,Bahia,43,38,11,10,17,42,51,-9,114,37.72
388,2021,19,Sport Recife,38,38,9,11,18,24,37,-13,114,33.33
389,2021,20,Chapecoense,15,38,1,12,25,27,67,-40,114,13.16

In [14]:
equipes_totais = brasileirao['equipe'].value_counts()
equipes_totais

São Paulo               20
Santos                  20
Flamengo                20
Fluminense              20
Corinthians             19
Internacional           19
Atlético Mineiro        19
Palmeiras               18
Grêmio                  18
Botafogo                17
Cruzeiro                17
Atlético Paranaense     15
Vasco da Gama           15
Coritiba                14
Goiás                   14
Figueirense             11
Vitória                 10
Bahia                   10
Sport                    9
Ponte Preta              9
Juventude                7
Fortaleza                7
Chapecoense              7
Atlético Goianiense      7
Ceará                    7
Avaí                     7
Paraná                   6
América Mineiro          5
Náutico                  5
São Caetano              4
Athletico Paranaense     4
Criciúma                 4
Guarani                  3
Portuguesa               3
Paysandu                 3
Cuiabá                   2
Santa Cruz               2
Sport Recife             2
RB Bragantino            2
Joinville                1
CSA                      1
Grêmio Prudente          1
América de Natal         1
Brasiliense              1
Santo André              1
Grêmio Barueri           1
Ipatinga                 1
Red Bull Bragantino      1
Name: equipe, dtype: int64

In [15]:
equipes_totaisDF2 = pd.DataFrame(equipes_totais)
equipes_totaisDF2

                      equipe
São Paulo                 20
Santos                    20
Flamengo                  20
Fluminense                20
Corinthians               19
Internacional             19
Atlético Mineiro          19
Palmeiras                 18
Grêmio                    18
Botafogo                  17
Cruzeiro                  17
Atlético Paranaense       15
Vasco da Gama             15
Coritiba                  14
Goiás                     14
Figueirense               11
Vitória                   10
Bahia                     10
Sport                      9
Ponte Preta                9
Juventude                  7
Fortaleza                  7
Chapecoense                7
Atlético Goianiense        7
Ceará                      7
Avaí                       7
Paraná                     6
América Mineiro            5
Náutico                    5
São Caetano                4
Athletico Paranaense       4
Criciúma                   4
Guarani                    3
Portuguesa                 3
Paysandu                   3
Cuiabá                     2
Santa Cruz                 2
Sport Recife               2
RB Bragantino              2
Joinville                  1
CSA                        1
Grêmio Prudente            1
América de Natal           1
Brasiliense                1
Santo André                1
Grêmio Barueri             1
Ipatinga                   1
Red Bull Bragantino        1

In [18]:
brasileirao.loc[brasileirao['equipe'] == 'Palmeiras']

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
27,2004,4,Palmeiras,79,46,22,13,11,72,47,25,138,57.25
51,2005,4,Palmeiras,70,42,20,10,12,81,65,16,126,55.56
85,2006,16,Palmeiras,44,38,12,8,18,58,70,-12,114,38.60
96,2007,7,Palmeiras,58,38,16,10,12,48,47,1,114,50.88
113,2008,4,Palmeiras,65,38,19,8,11,55,45,10,114,57.02
134,2009,5,Palmeiras,62,38,17,11,10,58,45,13,114,54.39
159,2010,10,Palmeiras,50,38,12,14,12,42,43,-1,114,43.86
180,2011,11,Palmeiras,50,38,11,17,10,43,39,4,114,43.86
207,2012,18,Palmeiras,34,38,9,7,22,39,54,-15,114,29.82
245,2014,16,Palmeiras,40,38,11,7,20,34,59,-25,114,35.09
258,2015,9,Palmeiras,53,38,15,8,15,60,51,9,114,46.49
270,2016,1,Palmeiras,80,38,24,8,6,62,32,30,114,70.18
291,2017,2,Palmeiras,63,38,19,6,13,61,45,16,114,55.26
310,2018,1,Palmeiras,80,38,23,11,4,64,26,38,114,70.18
332,2019,3,Palmeiras,74,38,21,11,6,61,32,29,114,64.91
356,2020,7,Palmeiras,58,38,15,13,10,51,37,14,114,50.88
372,2021,3,Palmeiras,66,38,20,6,12,58,43,15,114,57.89
390,2022,1,Palmeiras,81,38,23,12,3,66,27,39,114,71.05

In [19]:
brasileirao.loc[brasileirao['equipe'] == 'Athletico Paranaense']

,ano,posicao,equipe,pontos,jogos,vitorias,empates,derrotas,gols_marcados,gols_sofridos,saldo_de_gols,total_de_pontos,aproveitamento
334,2019,5,Athletico Paranaense,64,38,18,10,10,51,32,19,114,56.14
358,2020,9,Athletico Paranaense,53,38,15,8,15,38,36,2,114,46.49
383,2021,14,Athletico Paranaense,47,38,13,8,17,41,45,-4,114,41.23
395,2022,6,Athletico Paranaense,58,38,16,10,12,48,48,0,114,50.88

<h5>Qual equipe venceu o campeonato mais vezes ao longo dos anos?</h5>